<?php

namespace Blogger\BloggerBundle\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloggerInfoRepository extends \Doctrine\ORM\EntityRepository
{
    
}